apiVersion: v1
kind: Service
metadata:
  name: shepherd-web
  labels:
    app.kubernetes.io/name: shepherd-web
    app.kubernetes.io/component: web
spec:
  selector:
    app.kubernetes.io/name: shepherd-web
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
